// SIPENA Version Configuration
export const APP_VERSION = "2.4.92";
export const VERSION_DATE = "2026-06-23";

export const VERSION_HISTORY: Record<string, string> = {
  "2.4.92": "Membatalkan kompresi WebP pada unggahan OCR untuk menjaga ketajaman JPEG asli untuk akurasi AI, menghapus log audit Supabase demi privasi murid, serta menyajikan panduan visual WebP di modal dialog.",
  "2.4.91": "Optimasi konversi WebP (client-side) foto OCR untuk menghemat bandwidth jaringan, dan integrasi logging riwayat impor serta unggah gambar audit murid ke Supabase.",
  "2.4.90": "Peningkatan fitur Import Nilai dari Foto: penambahan panduan visual interaktif, algoritma fuzzy matching, pencocokan berbasis No. Urut (Absen), dropdown penyeleksi murid manual, serta konverter desimal skala 10.",
  "2.4.89": "Menghilangkan indikator zoom tingkat riil (zoom level %) dari footer tabel karena sudah tersedia pada toolbar utama.",
  "2.4.88": "Memindahkan badge mode edit ke toolbar atas sejajar dengan status freeze, serta merampingkan padding dan teks footer agar hemat ruang di layar mobile.",
  "2.4.87": "Integrasi fitur Tambah Kelas Baru langsung di halaman Input Nilai dan perapian visual label penjelas pada dropdown selektor kelas/mapel.",
  "2.4.86": "Redesain footer SpreadsheetTable dengan badge status mode interaktif, indikator zoom level reaktif, dan integrasi ikon metadata sekolah.",
  "2.4.85": "Menyusun standar wajib controlled state untuk dialog/overlay guna mendukung intersepsi back-gesture di perangkat mobile/PWA secara konsisten.",
  "2.4.84": "Menambahkan tombol Panduan Warna di footer tabel yang membuka modal overlay berisi informasi indikator KKM riil, kolom nilai khusus, dan setelan tema.",
  "2.4.83": "Menambahkan state nativeOrientation untuk sinkronisasi reaktif screen.orientation guna mencegah konflik rotasi ganda 180 derajat pada mode Fullscreen Maksimal.",
  "2.4.82": "Memperbaiki orientasi rotasi manual (Putar Kiri/Kanan) yang terbalik pada toolbar fullscreen agar sesuai dengan arah rotasi visual yang diharapkan.",
  "2.4.81": "Menyelaraskan orientasi rotasi manual (Putar Kiri/Kanan) dengan membalik pemetaan CSS transform dan native lock agar sesuai dengan arah gerak fisik pengguna.",
  "2.4.80": "Mencegah konflik rotasi terbalik 180 derajat pada mobile dengan menonaktifkan transform CSS rotasi secara dinamis apabila browser telah memutar viewport ke orientasi landscape secara native.",
  "2.4.79": "Mencegah rotasi otomatis (auto-rotate) saat masuk mode fullscreen di desktop dengan membatasi sinkronisasi screen.orientation khusus untuk perangkat mobile/tablet.",
  "2.4.78": "Perbaikan tumpang tindih (overlap) tombol Pembulatan pada toolbar fullscreen di desktop dengan melepas kelas w-full kondisional pada bagian view right-side, menyelaraskannya dengan CSS Container Query.",
  "2.4.77": "Memperbarui ikon rotasi menggunakan SVG presisi tinggi hasil tracing gambar rujukan flaticon, serta membalik logika arah rotasi (kiri dan kanan) agar tombol Putar Kiri/Kanan dan orientasi fisik terpetakan secara konsisten.",
  "2.4.76": "Mengganti ikon rotasi dengan desain panah melingkar berlawanan arah jarum jam (counter-clockwise) serta membalik logika penyesuaian rotasi kiri-kanan agar selaras dengan sudut pandang mata pengguna saat perangkat dimiringkan.",
  "2.4.75": "Perbaikan tata letak celah (gap) pada toolbar di luar mode fullscreen, penggunaan ikon rotasi kustom Flaticon, serta penambahan logika rotasi otomatis kiri/kanan berdasarkan orientasi fisik dan menu manual.",
  "2.4.74": "Menambahkan tombol Rotasi Layar (Rotate) di antara Zoom dan Search Siswa pada mode fullscreen.",
  "2.4.73": "Mengunci scroll body saat sidebar mobile terbuka, isolasi overscroll sidebar, dan menambahkan touch-none pada overlay mobile.",
  "2.4.72": "Revert simulasi rotasi layar dan penataan 3 kolom Baris 2 toolbar fullscreen, dengan tetap mempertahankan optimasi scrolling spreadsheet.",
  "2.4.71": "Optimasi performa mode fullscreen dengan direct DOM scroll updates.",
  "2.4.70": "Batas tinggi dropdown Select agar tidak terpotong di screen pendek/landscape dan opsi dapat digulir.",
  "2.4.69": "Perbaikan duplikasi tombol tutup dan pelebaran dinamis search box fullscreen.",
  "2.4.68": "Prioritas layout 1 baris fullscreen untuk viewport lebar.",
  "2.4.67": "Penyelarasan layout fullscreen & visual order zoom-pencarian landscape sempit.",
  "2.4.66": "Perbaikan border fokus search siswa dan dropdown menu terpotong di mode fullscreen sempit.",
  "2.4.65": "Perbaikan hilangnya tombol kelola/rumus/pembulatan pada mode Fullscreen di viewport sempit.",
  "2.4.64": "Transisi tinggi kontainer tab secara dua arah (expand/shrink) yang mulus dan penyesuaian scroll offset dinamis untuk sticky header.",
  "2.4.63": "Transisi tinggi minimal kontainer tab secara smooth dan sinkronisasi smooth scroll halaman saat tab berubah.",
  "2.4.62": "Penambahan animasi fade-in pada tab panel Input Nilai untuk transisi yang lebih halus.",
  "2.4.61": "Penghapusan otomatis locked min-height pasca-transisi tab untuk menyesuaikan tinggi secara dinamis.",
  "2.4.60": "Fokus scroll otomatis ke kontainer tabel saat berpindah dari Struktur ke Input Nilai.",
  "2.4.59": "Perombakan Struktur BAB & Tugas dengan accordion modern, menu kebab titik tiga, tombol navigasi lanjut, serta aksi duplikasi BAB/Tugas.",
  "2.4.58": "Audit menyeluruh empty-state dropdown di seluruh aplikasi, perbaikan bug di panel prediksi siswa dashboard, penambahan standar dokumentasi.",
  "2.4.57": "Empty-state guard diperluas ke Attendance, StudentRankings, dan ParentPortal, layout bento mobile bento diperbaiki, dan toolbar landscape viewport pendek dioptimasi.",
  "2.4.56": "Laporan Nilai menyamakan perilaku tabel dengan Input Nilai, kartu Mata Pelajaran lebih responsif, touch-scroll guard diperkuat, dan ekspor ranking memakai tinggi baris lebih efisien.",
  "2.4.55": "Input Nilai memadatkan layout berdasarkan observasi viewport mobile terbaru dan jalur auth lockout reset kini dikunci lewat RLS function-only.",
  "2.4.54": "Editor nama BAB dan Tugas kini memakai lebar viewport yang tersedia, responsif di mobile/tablet/desktop, dan tombol aksinya tetap nyaman ditekan.",
  "2.4.53": "Perpindahan tab Input Nilai menjaga tinggi panel agar posisi scroll halaman tidak meloncat ke atas.",
  "2.4.52": "Divider tab Input Nilai dirapikan tanpa celah dan disambungkan ke panel sebagai satu siluet binder.",
  "2.4.51": "Tab Struktur BAB dan Input Nilai kini berbentuk divider binder yang menyatu langsung dengan panel konten.",
  "2.4.50": "Input Nilai memperbaiki klik toolbar, menyatukan tab dengan panel, memperkuat kontras tombol/menu, dan menstandarkan scroll internal lintas halaman.",
  "2.4.49": "Input Nilai memperbaiki scroll chaining mobile, modal fullscreen, hint prediksi sementara, toolbar touch, visual proteksi, dan update PWA otomatis anti-stuck.",
  "2.4.48": "Input Nilai memperbaiki toolbar aksi, scroll touch kolom frozen, back gesture fullscreen, tab mode, dan menahan tooltip prediksi di fullscreen mobile.",
  "2.4.47": "Toolbar Input Nilai kini menampilkan scrollbar horizontal tipis saat tombol meluap agar area yang bisa digeser lebih mudah dikenali.",
  "2.4.46": "Input Nilai memperjelas warna nilai Cukup, menambahkan tooltip header tabel, memperbesar scrollbar desktop, dan menyiapkan sync agregat viewport lokal.",
  "2.4.45": "Input Nilai memperjelas nama fullscreen teknis, membaca safe-area native mobile, membuat toolbar tabel portrait lebih compact, dan menambahkan telemetry viewport senyap.",
  "2.4.44": "Input Nilai memadatkan header dan toolbar tabel pada viewport landscape pendek agar area tabel lebih luas dan tombol tidak menyisakan ruang kosong.",
  "2.4.43": "Input Nilai menambahkan pilihan Fullscreen Tabel dan Fullscreen Browser agar mode layar penuh lebih jelas.",
  "2.4.42": "Input Nilai menutup menu Freeze saat klik luar area atau Escape dan memperbaiki kontras hover menu Proteksi.",
  "2.4.41": "Input Nilai memperlebar edit BAB/tugas, memperbaiki layer menu Freeze, dan menambahkan shadow pemisah header tabel.",
  "2.4.40": "Input Nilai memperbaiki toolbar/dropdown responsif, scroll touch tabel, info bar, dan menambahkan standar viewport untuk mencegah regresi UI.",
  "2.4.39": "Input Nilai memperjelas header, memadatkan toolbar fullscreen landscape, dan memperbaiki warna Cukup tanpa garis bawah.",
  "2.4.38": "Fullscreen Input Nilai memperbaiki scroll vertikal agar tetap bekerja pada tabel dan tidak berpindah ke halaman belakang.",
  "2.4.37": "Tombol, dropdown, tab, select, dan menu interaktif dibuat tidak bisa memblok teks agar interaksi terasa lebih bersih.",
  "2.4.36": "Nilai Kurang dan Cukup kini sama-sama memakai garis bawah dengan warna merah dan amber yang lebih cerah agar lebih mudah dibedakan.",
  "2.4.35": "Nilai di bawah KKM kini memakai penanda merah yang lebih kuat dengan garis bawah agar berbeda jelas dari nilai Cukup.",
  "2.4.34": "Warna merah untuk nilai di bawah KKM dibuat lebih tegas dengan teks lebih tebal dan kontras Rapor yang lebih kuat.",
  "2.4.33": "Warna indikator KKM pada tabel Input Nilai diperjelas agar nilai Kurang dan Cukup lebih mudah dibedakan.",
  "2.4.32": "Input Nilai memperbaiki fullscreen landscape, warna Rapor mengikuti indikator KKM, teks nilai di bawah KKM lebih jelas, dan Ranking Siswa fokus ke ranking keseluruhan.",
  "2.4.31": "Tabel Input Nilai memperjelas warna Rapor, STS/SAS, hover baris-kolom, toolbar fullscreen/mobile, scroll chaining, dan perilaku pencarian siswa.",
  "2.4.30": "Tabel Input Nilai memperbaiki warna Theme A/B, hover baris dan kolom, header final yang terpotong, persistensi warna tabel, serta target pembulatan Rapor/Rata-rata.",
  "2.4.29": "Pengaturan Warna Tabel Nilai ditambahkan dengan Setting A sebagai default, Setting B untuk tampilan warna saat ini, dan Setting C sebagai slot warna akan datang.",
  "2.4.28": "Deploy frontend diperkuat dengan blank-screen guard yang memverifikasi asset JS/CSS production dan render React sebelum rilis dianggap aman.",
  "2.4.27": "Tabel Input Nilai merapikan fullscreen mobile dengan header STS/SAS merged, toolbar tanpa celah kosong, dan scroll touch landscape yang lebih stabil.",
  "2.4.26": "Tabel Input Nilai dibuat lebih responsif dengan nama siswa yang wrap penuh, pencarian siswa tanpa ikon yang menutup teks, dan pengaturan pembulatan kolom Rapor.",
  "2.4.25": "Kolom Rata-rata pada tabel Input Nilai diberi warna cell abu-abu netral agar lebih jelas sebagai kolom kalkulasi dan pembatas antar BAB.",
  "2.4.24": "Tabel Input Nilai diperjelas dengan highlight baris saat hover, label Rata-rata, warna header BAB/STS/SAS yang lebih terarah, dan pembungkus responsive yang lebih aman di mobile.",
  "2.4.23": "Penyimpanan nilai diperbaiki dengan repair duplikasi database yang mengarsipkan row lama, menambahkan unique constraint, dan menyatukan edit langsung ke pipeline RPC atomic.",
  "2.4.22": "Backup Lengkap Nilai menambahkan konfirmasi mode perlindungan metadata, panduan Excel yang lebih informatif, dan restore kini menghormati backup yang dikunci agar edit sheet Nilai tidak override _grades.",
  "2.4.21": "Restore Backup Nilai kini membaca perubahan nilai pada sheet Nilai yang terlihat di Excel, bukan hanya metadata _grades tersembunyi, sehingga edit manual di workbook terdeteksi saat preview.",
  "2.4.20": "Restore Backup Nilai menghapus cache sesi upload lama saat file baru atau file yang sama dipilih ulang, sehingga preview dan konflik selalu dihitung dari workbook terbaru.",
  "2.4.19": "Restore Backup Nilai memperbaiki posisi aksi footer agar sejajar dengan dropdown mode, mencegah dialog overwrite menutup modal restore utama, dan memperjelas tooltip reset spreadsheet.",
  "2.4.18": "Restore Backup Nilai menyempurnakan footer mode penuh dan timpa, memperjelas dialog pilihan overwrite dengan backdrop blur, menata warna tombol sesuai aksi, serta menjelaskan catatan duplikat _grades secara lebih faktual.",
  "2.4.17": "Restore Backup Nilai diperbaiki agar mode tampil sebagai dropdown overlay, pilihan timpa dibuka lewat dialog khusus, inspector detail hanya muncul setelah cell diklik, dan duplikat nilai identik tidak lagi menjadi catatan konflik.",
  "2.4.16": "Restore Backup Nilai dibuat interaktif dengan side inspector, pemilihan mode di footer preview, konfirmasi akhir read-only, dan validasi identitas siswa yang lebih ketat.",
  "2.4.15": "Restore Backup Nilai kini memilih baris backup kanonik saat ada duplikat, menampilkan catatan per nilai lewat tooltip, dan memperbesar area drag-drop upload.",
  "2.4.14": "Preview Restore Backup Nilai disamakan langsung dengan struktur modal dan tabel spreadsheet Import/Ekspor agar sticky column, scroll, dan warna status konsisten.",
  "2.4.13": "Preview Restore Backup Nilai mengikuti responsivitas spreadsheet Import, mengunci scroll tabel di dalam modal, dan menghapus tombol tutup redundan.",
  "2.4.12": "Modal Restore Backup Nilai dibuat hampir memenuhi layar dan tabel preview memakai grid responsif dinamis dengan scroll serta warna status yang lebih jelas.",
  "2.4.11": "Preview Restore Backup Nilai dirapikan agar tabel tidak terpotong, responsif di desktop, dan memakai tampilan ringkas di mobile.",
  "2.4.10": "Restore Backup Nilai kini memiliki preview tabel siswa dan kolom nilai agar status tambah, timpa, sama, dilewati, dan konflik terlihat sebelum restore.",
  "2.4.9": "Backup dan Restore Nilai diperketat agar metadata Supabase tetap presisi, row legacy tidak tertukar konteks, dan restore tidak memproses nilai ganda.",
  "2.4.8": "Restore Backup Nilai ditambahkan dengan preview, validasi konteks, dan konfirmasi agar nilai tidak tertimpa tanpa persetujuan.",
  "2.4.7": "Tampilan Export Nilai dirapikan dan template/export nilai dikunci lebih akurat ke semester serta tahun ajaran aktif.",
  "2.4.6": "SmartImport nilai diperkuat dengan validasi Excel/AI yang lebih ketat, rollback struktur baru saat import gagal, dan akses keyboard pada preview.",
  "2.4.5": "Proteksi login bertingkat ditambahkan dengan request reset waiting time melalui reCAPTCHA dan panel Admin SIPENA.",
  "2.4.4": "Proteksi login diperkuat dengan kunci sementara setelah tiga kali password salah dan arahan reset password yang lebih jelas.",
  "2.4.3": "SmartImport nilai dibuat lebih aman dengan Import Aman default, validasi Excel lebih ketat, dan preview yang lebih sinkron.",
  "2.4.2": "Ranking per mata pelajaran dikunci mengikuti semester yang dipilih dan data legacy tanpa semester hanya dipakai sebagai fallback.",
  "2.4.1": "Perhitungan Ranking Siswa diperbaiki agar ranking keseluruhan dan ranking per mata pelajaran akurat pada filter mapel dan mode semua semester.",
  "2.4.0": "Rombakan Studio Ekspor Presensi: side panel dipadatkan, keterangan vertikal PDF kini benar-benar tampil sebagai cell merged, jarak garis pada Style Signature dipresisi, dan kontrol presisi TTD (drag + D-Pad) dirombak agar bekerja akurat di setiap zoom preview.",
  "2.3.100": "Sinkronisasi metrik layout ekspor dan loader latar belakang diperkuat agar preview, PDF, dan PNG tetap konsisten saat aplikasi berpindah fokus.",
  "2.3.99": "Keterangan Presensi, rekap, dan pembaruan aplikasi dipoles agar hasil ekspor lebih stabil dan lebih mudah dipahami.",
  "2.3.98": "Sinkronisasi ekspor Presensi, Keterangan dua kolom, penempatan signature, dan alur pembaruan aplikasi diperbaiki.",
  "2.3.97": "Header Presensi didesain ulang, footer dirapikan, dan pola deteksi pembaruan aplikasi dibuat lebih andal.",
  "2.3.96": "Polish ekspor Presensi: merge cell ringkasan, posisi signature default, border rounded, dan penyelarasan banner.",
  "2.3.95": "Perbaikan sinkronisasi ekspor Presensi: header rekap, blank page, dan reset posisi signature.",
  "2.3.94": "Polish ekspor Presensi: nama hari, tinggi baris, drag signature, dan keterbacaan nama siswa.",
  "2.3.93": "Presensi difokuskan agar tetap muat satu halaman secara lebih aman dengan header, kolom, dan ringkasan yang tidak saling bertabrakan.",
  "2.3.92": "Refactor WYSIWYG Presensi dengan satu layout plan untuk preview, print, PDF, dan PNG.",
  "2.3.91": "Rentang zoom preview diperluas dan sinkronisasi skala header Presensi diperbaiki.",
  "2.3.90": "Ekspor PDF Presensi beralih ke jalur native dengan hasil yang lebih presisi.",
  "2.3.89": "Metrik preview dan export diselaraskan agar hasil WYSIWYG lebih konsisten.",
  "2.3.88": "Ekspor PDF native dan dokumentasi publik dirapikan agar tetap informatif tanpa membuka detail internal yang tidak perlu.",
  "2.3.86": "Preview ekspor Presensi dan kontrol style mulai disatukan.",
  "2.3.85": "Pengalaman scroll tabel dan layout halaman dibuat lebih stabil.",
  "2.3.84": "Quick action dashboard diperluas.",
  "2.3.83": "Dialog akademik dibuat lebih responsif.",
  "2.3.82": "Visual clarity section, card, dan tab ditingkatkan.",
  "2.3.81": "Data changelog dan dokumentasi dirapikan.",
  "2.3.80": "Optimasi performa dan stabilitas untuk halaman besar dan komponen berat.",
  "2.3.79": "Pengalaman mobile dipoles untuk area sentuh dan toolbar.",
  "2.3.78": "Konsistensi dark mode dan spacing antarkomponen ditingkatkan.",
  "2.3.77": "Penyempurnaan responsivitas dialog dan scroll lintas halaman.",
  "2.3.76": "Pengelolaan tanggal libur dan tooltip mobile dibuat lebih nyaman.",
  "2.3.75": "Hari libur nasional, konfigurasi Jumlah, dan baris persentase ditambahkan.",
  "2.3.74": "Rekap bulanan Presensi diperjelas dengan urutan status dan kolom Jumlah.",
  "2.3.73": "Sinkronisasi data Presensi historis diperbaiki.",
  "2.3.72": "Preview ekspor signature dan data siswa dipoles.",
  "2.3.71": "Perbaikan minor Presensi harian dan rekap bulanan.",
  "2.3.70": "Signature pada Ranking Siswa dan pembaruan panel AI dirapikan.",
  "2.3.69": "Signature multi-signer dan live preview diperluas.",
  "2.3.68": "Fondasi integrasi signature untuk ekspor diperkuat.",
  "2.3.67": "Skema pengaturan signature v2 dan utilitas ekspor signature ditambahkan.",
  "2.3.66": "Rencana awal signature ekspor dan perbaikan minor UI.",
  "2.3.65": "Penyempurnaan panel AI dan detail kecil antarmuka.",
  "2.3.64": "Persistensi tim pengembang, tautan sosial, dan aksi massal Presensi diperbarui.",
  "2.3.63": "PageHeader, panel AI, preview file, dan manajemen tim diperluas.",
  "2.3.62": "Audit touch target dan toolbar mobile dilakukan lebih menyeluruh.",
  "2.3.61": "Import multi-sheet dan portal orang tua diperluas.",
  "2.3.60": "Sistem semester komprehensif diperkenalkan.",
  "2.3.59": "Perhitungan ranking dan filter semester diperbaiki.",
  "2.3.58": "Perbaikan AI, import Excel, dan export loader.",
  "2.3.57": "Perbaikan loader, chat AI, data portal, dan import nilai.",
  "2.3.56": "Perbaikan blank loader, sidebar, kamera, dan identitas visual.",
  "2.3.55": "Iterasi AI dengan lampiran file, vision, dan ringkasan otomatis.",
  "2.3.54": "Iterasi AI dengan session pinning dan blok kode yang lebih baik.",
  "2.3.53": "Iterasi AI dengan fullscreen dan manajemen sesi.",
  "2.3.52": "Chat AI, ExportLoaderOverlay, dan halaman Terms diperkenalkan.",
  "2.3.51": "Portal data, kartu Reports, dan overlay ekspor dipoles.",
  "2.3.50": "Legenda kalender, QR portal, dan kontrol granular diperluas.",
  "2.3.49": "Rumus persentase Presensi dan badge hari efektif diperjelas.",
  "2.3.48": "Layout sidebar persisten dan overview data dirapikan.",
  "2.3.47": "Preferensi Presensi, sinkronisasi hari libur, dan konfigurasi Jumlah dibuat lebih fleksibel.",
  "2.3.46": "Scroll horizontal tabel dan tooltip rekap diperbaiki.",
  "2.3.45": "Badge libur interaktif dan drag-drop signature dipoles.",
  "2.3.44": "Autentikasi dan perlindungan akses dibuat lebih kuat.",
  "2.3.43": "Wrapping nama panjang dan perapian dokumentasi dilakukan.",
  "2.3.42": "Catatan Presensi mobile, lupa sandi, dan notifikasi aplikasi ditingkatkan.",
  "2.3.41": "Perhitungan ranking dan null handling diperbaiki.",
  "2.3.40": "Toast, activity log, dan responsivitas Presensi dipoles.",
  "2.3.39": "Presensi harian responsif, kalender Indonesia, dan ekspor PNG ditingkatkan.",
  "2.3.38": "Error boundary, skeleton, throttle, dan perlindungan input diperkuat.",
  "2.3.37": "Pengaturan Presensi responsif dan pesan auth diperbaiki.",
  "2.3.36": "UI overhaul dan perbaikan ScrollArea Presensi.",
  "2.3.35": "PNG export HD, batch event, dan pencarian mendalam diperluas.",
  "2.3.34": "Readability, batch holiday, dan ekspor mobile dipoles.",
  "2.3.33": "Perbaikan Presensi, ekspor full-width, dan pencarian.",
  "2.3.32": "Presensi V2, Global Search, dan validasi auth diperbarui.",
  "2.3.31": "Orientasi PNG, posisi signature, dan preview data diperbaiki.",
  "2.3.30": "Panel signature, tanggal kustom, dan opsi font diperluas.",
  "2.3.29": "Multi-signer hingga empat penanda tangan diperkenalkan.",
  "2.3.28": "Skema pengaturan signature v2 diperluas.",
  "2.3.27": "Utilitas signature untuk berbagai format ekspor ditambahkan.",
  "2.3.26": "Fondasi integrasi signature pada dialog ekspor.",
  "2.3.25": "Dokumentasi signature ekspor dan perbaikan minor sidebar.",
  "2.3.24": "Manajemen tim pengembang di Admin diperbarui.",
  "2.3.23": "Animasi teks AI dan context menu sidebar dipoles.",
  "2.3.22": "Data changelog dipisahkan ke file tersendiri.",
  "2.3.21": "Preview file mendukung zoom, rotate, dan viewer tambahan.",
  "2.3.20": "Panel pengaturan AI diperluas.",
  "2.3.19": "PageHeader reusable dengan breadcrumb ditambahkan.",
  "2.3.18": "Audit touch target dan toolbar mobile.",
  "2.3.17": "Konsistensi dark mode dan button sizing.",
  "2.3.16": "Import multi-sheet untuk kebutuhan akademik.",
  "2.3.15": "Portal orang tua detail nilai per mata pelajaran.",
  "2.3.14": "Persetujuan akses data sensitif diperjelas.",
  "2.3.13": "Context menu sidebar AI ditambahkan.",
  "2.3.12": "Sidebar sesi AI dirapikan.",
  "2.3.11": "Rencana Rapor Online dan OCR diperluas.",
  "2.3.10": "Performa laporan besar dan pemuatan komponen berat ditingkatkan.",
  "2.3.9": "Filter semester dan saran tahun diperbaiki.",
  "2.3.8": "Ekspor signature dan preview data dipoles.",
  "2.3.7": "Sistem semester v2 dengan hierarki periode yang lebih konsisten.",
};
