// SIPENA Version Configuration
export const APP_VERSION = "2.4.0";
export const VERSION_DATE = "2026-04-25";

export const VERSION_HISTORY: Record<string, string> = {
  "2.4.0": "Rombakan Studio Ekspor Presensi: side panel dipadatkan, keterangan vertikal PDF kini benar-benar tampil sebagai cell merged, jarak garis pada Style Signature dipresisi, dan kontrol presisi TTD (drag + D-Pad) dirombak agar bekerja akurat di setiap zoom preview.",
  "2.3.100": "Sinkronisasi metrik layout ekspor dan loader latar belakang diperkuat agar preview, PDF, dan PNG tetap konsisten saat aplikasi berpindah fokus.",
  "2.3.99": "Keterangan Presensi, rekap, dan pembaruan aplikasi dipoles agar hasil ekspor lebih stabil dan lebih mudah dipahami.",
  "2.3.98": "Sinkronisasi ekspor Presensi, Keterangan dua kolom, penempatan signature, dan alur pembaruan aplikasi diperbaiki.",
  "2.3.97": "Header Presensi didesain ulang, footer dirapikan, dan pola deteksi pembaruan aplikasi dibuat lebih andal.",
  "2.3.96": "Polish ekspor Presensi: merge cell ringkasan, posisi signature default, border rounded, dan penyelarasan banner.",
  "2.3.95": "Perbaikan sinkronisasi ekspor Presensi: header rekap, blank page, dan reset posisi signature.",
  "2.3.94": "Polish ekspor Presensi: nama hari, tinggi baris, drag signature, dan keterbacaan nama siswa.",
  "2.3.93": "Presensi difokuskan agar tetap muat satu halaman secara lebih aman dengan header, kolom, dan ringkasan yang tidak saling bertabrakan.",
  "2.3.92": "Refactor WYSIWYG Presensi dengan satu layout plan untuk preview, print, PDF, dan PNG.",
  "2.3.91": "Rentang zoom preview diperluas dan sinkronisasi skala header Presensi diperbaiki.",
  "2.3.90": "Ekspor PDF Presensi beralih ke jalur native dengan hasil yang lebih presisi.",
  "2.3.89": "Metrik preview dan export diselaraskan agar hasil WYSIWYG lebih konsisten.",
  "2.3.88": "Ekspor PDF native dan dokumentasi publik dirapikan agar tetap informatif tanpa membuka detail internal yang tidak perlu.",
  "2.3.86": "Preview ekspor Presensi dan kontrol style mulai disatukan.",
  "2.3.85": "Pengalaman scroll tabel dan layout halaman dibuat lebih stabil.",
  "2.3.84": "Quick action dashboard diperluas.",
  "2.3.83": "Dialog akademik dibuat lebih responsif.",
  "2.3.82": "Visual clarity section, card, dan tab ditingkatkan.",
  "2.3.81": "Data changelog dan dokumentasi dirapikan.",
  "2.3.80": "Optimasi performa dan stabilitas untuk halaman besar dan komponen berat.",
  "2.3.79": "Pengalaman mobile dipoles untuk area sentuh dan toolbar.",
  "2.3.78": "Konsistensi dark mode dan spacing antarkomponen ditingkatkan.",
  "2.3.77": "Penyempurnaan responsivitas dialog dan scroll lintas halaman.",
  "2.3.76": "Pengelolaan tanggal libur dan tooltip mobile dibuat lebih nyaman.",
  "2.3.75": "Hari libur nasional, konfigurasi Jumlah, dan baris persentase ditambahkan.",
  "2.3.74": "Rekap bulanan Presensi diperjelas dengan urutan status dan kolom Jumlah.",
  "2.3.73": "Sinkronisasi data Presensi historis diperbaiki.",
  "2.3.72": "Preview ekspor signature dan data siswa dipoles.",
  "2.3.71": "Perbaikan minor Presensi harian dan rekap bulanan.",
  "2.3.70": "Signature pada Ranking Siswa dan pembaruan panel AI dirapikan.",
  "2.3.69": "Signature multi-signer dan live preview diperluas.",
  "2.3.68": "Fondasi integrasi signature untuk ekspor diperkuat.",
  "2.3.67": "Skema pengaturan signature v2 dan utilitas ekspor signature ditambahkan.",
  "2.3.66": "Rencana awal signature ekspor dan perbaikan minor UI.",
  "2.3.65": "Penyempurnaan panel AI dan detail kecil antarmuka.",
  "2.3.64": "Persistensi tim pengembang, tautan sosial, dan aksi massal Presensi diperbarui.",
  "2.3.63": "PageHeader, panel AI, preview file, dan manajemen tim diperluas.",
  "2.3.62": "Audit touch target dan toolbar mobile dilakukan lebih menyeluruh.",
  "2.3.61": "Import multi-sheet dan portal orang tua diperluas.",
  "2.3.60": "Sistem semester komprehensif diperkenalkan.",
  "2.3.59": "Perhitungan ranking dan filter semester diperbaiki.",
  "2.3.58": "Perbaikan AI, import Excel, dan export loader.",
  "2.3.57": "Perbaikan loader, chat AI, data portal, dan import nilai.",
  "2.3.56": "Perbaikan blank loader, sidebar, kamera, dan identitas visual.",
  "2.3.55": "Iterasi AI dengan lampiran file, vision, dan ringkasan otomatis.",
  "2.3.54": "Iterasi AI dengan session pinning dan blok kode yang lebih baik.",
  "2.3.53": "Iterasi AI dengan fullscreen dan manajemen sesi.",
  "2.3.52": "Chat AI, ExportLoaderOverlay, dan halaman Terms diperkenalkan.",
  "2.3.51": "Portal data, kartu Reports, dan overlay ekspor dipoles.",
  "2.3.50": "Legenda kalender, QR portal, dan kontrol granular diperluas.",
  "2.3.49": "Rumus persentase Presensi dan badge hari efektif diperjelas.",
  "2.3.48": "Layout sidebar persisten dan overview data dirapikan.",
  "2.3.47": "Preferensi Presensi, sinkronisasi hari libur, dan konfigurasi Jumlah dibuat lebih fleksibel.",
  "2.3.46": "Scroll horizontal tabel dan tooltip rekap diperbaiki.",
  "2.3.45": "Badge libur interaktif dan drag-drop signature dipoles.",
  "2.3.44": "Autentikasi dan perlindungan akses dibuat lebih kuat.",
  "2.3.43": "Wrapping nama panjang dan perapian dokumentasi dilakukan.",
  "2.3.42": "Catatan Presensi mobile, lupa sandi, dan notifikasi aplikasi ditingkatkan.",
  "2.3.41": "Perhitungan ranking dan null handling diperbaiki.",
  "2.3.40": "Toast, activity log, dan responsivitas Presensi dipoles.",
  "2.3.39": "Presensi harian responsif, kalender Indonesia, dan ekspor PNG ditingkatkan.",
  "2.3.38": "Error boundary, skeleton, throttle, dan perlindungan input diperkuat.",
  "2.3.37": "Pengaturan Presensi responsif dan pesan auth diperbaiki.",
  "2.3.36": "UI overhaul dan perbaikan ScrollArea Presensi.",
  "2.3.35": "PNG export HD, batch event, dan pencarian mendalam diperluas.",
  "2.3.34": "Readability, batch holiday, dan ekspor mobile dipoles.",
  "2.3.33": "Perbaikan Presensi, ekspor full-width, dan pencarian.",
  "2.3.32": "Presensi V2, Global Search, dan validasi auth diperbarui.",
  "2.3.31": "Orientasi PNG, posisi signature, dan preview data diperbaiki.",
  "2.3.30": "Panel signature, tanggal kustom, dan opsi font diperluas.",
  "2.3.29": "Multi-signer hingga empat penanda tangan diperkenalkan.",
  "2.3.28": "Skema pengaturan signature v2 diperluas.",
  "2.3.27": "Utilitas signature untuk berbagai format ekspor ditambahkan.",
  "2.3.26": "Fondasi integrasi signature pada dialog ekspor.",
  "2.3.25": "Dokumentasi signature ekspor dan perbaikan minor sidebar.",
  "2.3.24": "Manajemen tim pengembang di Admin diperbarui.",
  "2.3.23": "Animasi teks AI dan context menu sidebar dipoles.",
  "2.3.22": "Data changelog dipisahkan ke file tersendiri.",
  "2.3.21": "Preview file mendukung zoom, rotate, dan viewer tambahan.",
  "2.3.20": "Panel pengaturan AI diperluas.",
  "2.3.19": "PageHeader reusable dengan breadcrumb ditambahkan.",
  "2.3.18": "Audit touch target dan toolbar mobile.",
  "2.3.17": "Konsistensi dark mode dan button sizing.",
  "2.3.16": "Import multi-sheet untuk kebutuhan akademik.",
  "2.3.15": "Portal orang tua detail nilai per mata pelajaran.",
  "2.3.14": "Persetujuan akses data sensitif diperjelas.",
  "2.3.13": "Context menu sidebar AI ditambahkan.",
  "2.3.12": "Sidebar sesi AI dirapikan.",
  "2.3.11": "Rencana Rapor Online dan OCR diperluas.",
  "2.3.10": "Performa laporan besar dan pemuatan komponen berat ditingkatkan.",
  "2.3.9": "Filter semester dan saran tahun diperbaiki.",
  "2.3.8": "Ekspor signature dan preview data dipoles.",
  "2.3.7": "Sistem semester v2 dengan hierarki periode yang lebih konsisten.",
};
