// SIPENA Version Configuration
export const APP_VERSION = "2.3.101";
export const VERSION_DATE = "2026-04-24";

export const VERSION_HISTORY = {
  "2.3.101": "Continuation Keterangan + TTD Guide Fix - halaman lanjutan tidak lagi merender header tabel kosong di balik blok Keterangan, format tanggal Keterangan menjadi rentang bulan singkat seperti '15 - 17 Apr — ...', pewarnaan isi Keterangan dibedakan menurut sumber (nasional/custom/event), border bantuan TTD diselaraskan ke area render TTD yang sebenarnya, preview canvas PDF mengikuti RenderParameters pdf.js terbaru, plan integrasi Web Service Dapodik ditambahkan",
  "2.3.100": "Shared Shell Metrics + Background-Resilient Export Loader - extract ATTENDANCE_SHELL_MM/MARGIN_MM/TOLERANCE ke exportEngine/attendanceShellMetrics.ts sebagai single source of truth (planner & PDF engine import konstanta yang sama → preview dan export pasti sinkron, mustahil drift), background-resilient timer (lib/backgroundTimer.ts) berbasis MessageChannel sehingga ExportLoaderOverlay tetap berjalan saat tab di-minimize / browser di-background (sebelumnya throttled ~1 Hz), GSAP digantikan CSS transitions untuk overlay yang lebih ringan, signature breathing-buffer ikut konstanta bersama",
  "2.3.99": "Fix TTD Overlap & Pagination - pisahkan flag isLastPage / hasSummaryRows / drawSignatureHere / isSignatureOnlyPage sehingga TTD tidak pernah duplikat (sebelumnya tergambar di halaman tabel + halaman dedicated), TOTAL & PERSENTASE tetap muncul saat planner men-spawn dedicated signature page, preview AttendancePrintDocument disinkronkan dengan flag baru",
  "2.3.98": "Smart TTD pagination & types hardening - planner auto-pindahkan TTD ke halaman dedicated saat data sedikit (15-25 siswa) sehingga tidak menumpuk tabel, opsi signaturePageIndex untuk memindah TTD antar halaman secara manual, hook useRepeatPress untuk arrow Kontrol Presisi yang bisa ditekan & tahan, perbaikan typing third-party (react-konva/recharts/input-otp) agar build pipeline bersih, pewarnaan rekap S/L tetap sinkron",
  "2.3.97": "Attendance Header Redesign + PWA Update Fix - banner tunggal Plus Jakarta Sans (judul, kelas, bulan, pills siswa/hari/format), timestamp pindah ke footer, 'SIPENA | Dokumen Presensi' & 'Halaman X/Y' di header dihapus, tabel PDF dengan rounded outer border (sinkron preview), planner topBanner=18mm, PWA: hapus dual SW registration, polling update tiap 30s + on focus/visibilitychange/online sehingga banner update tampil tanpa perlu incognito",
  "2.3.96": "Attendance Export Polish - merge cell TOTAL & PERSENTASE (No+Nama+NISN dalam 1 cell, kolom hari dalam 1 cell), default TTD lebih rapat (3mm di atas zona aman), tabel preview dengan rounded corners, sinkronisasi banner radius preview ↔ PDF (mm(2) konsisten), plan dokumen redesign header lengkap",
  "2.3.95": "Attendance Export Sync Fix - bug 'Jml→Jm' diperbaiki (lebar rekap min 7.4mm + overflow visible), planner row height +0.45mm overhead untuk autoTable, pageBreak:'auto' menghilangkan halaman pertama kosong, NISN no-wrap, tombol Reset posisi TTD di live preview",
  "2.3.94": "Attendance Export Polish - nama hari selalu 3 huruf (Sen/Sel/Rab), tinggi baris menyesuaikan nama panjang (tidak terpotong), badge mode auto-fit dihilangkan dari header, TTD bisa di-drag bebas di live preview seperti ekspor lain dan tidak terpotong saat ekspor PDF/PNG",
  "2.3.93": "Attendance Export Fit Fix - default 1 halaman per bulan + tanda tangan, header hari abbreviated (Sn/Sl/Rb) tidak tertumpuk, tinggi header row 2x untuk dual baris hari/tanggal, kolom Nama lebih lebar, baris TOTAL/PERSENTASE tidak terpotong",
  "2.3.92": "Attendance WYSIWYG Refactor - layout plan tunggal (attendancePrintLayout), AttendancePrintDocument renderer terpadu untuk preview/print/PDF/PNG, smart grouping libur (rentang tanggal), auto-fit 3 tahap (base/soft/hard), pagination vertikal aman tanpa baris terpotong",
  "2.3.91": "Preview Zoom 25-200% & Header Overflow Fix - rentang zoom diperluas, sinkronisasi PX_PER_MM (3.78) preview presensi dengan engine PDF, header hari tidak lagi tertumpuk",
  "2.3.90": "Attendance Native PDF Export - ekspor presensi native jsPDF (bukan convert gambar), 1 halaman per bulan + tanda tangan, word-wrap nama siswa",
  "2.3.89": "WYSIWYG Export Sync - shared metrics antara PDF engine dan live preview, zero gap font size/padding/row height, PX_PER_MM presisi 96dpi",
  "2.3.88": "Real PDF Export & Security Audit - ekspor PDF asli tanpa convert gambar, presisi ukuran A4/F4, audit changelog keamanan, plan unified export",
  "2.3.86": "Unify Attendance Export Preview & Style Controls - penyatuan preview ekspor presensi dengan kontrol gaya yang lebih baik, visual consistency, dan optimasi layout",
  "2.3.85": "Smart Scroll Table & Unified Scroll Experience - perbaikan scroll horizontal tabel tanpa konflik sidebar",
  "2.3.84": "Dashboard Quick Actions Enhancement - tombol cepat Presensi dan Ranking di dashboard",
  "2.3.83": "Dialog Responsif BAB dan Tugas - dialog tidak terpotong di mobile/tablet",
  "2.3.82": "Visual Clarity Overhaul - section headers, card styling, tab navigation lebih jelas",
  "2.3.81": "Changelog Gap Fill & Documentation - pengisian gap changelog dan dokumentasi sistem",
  "2.3.80": "Performance Optimization & Bug Fixes - indexing database, lazy loading, memory leak fix",
  "2.3.79": "Mobile UX Improvements - touch target 44px, toolbar optimization, grouped actions",
  "2.3.78": "Dark Mode Consistency & UI Polish - semantic token audit, button spacing konsisten",
  "2.3.77": "Dialog responsif, visual clarity, unified scroll, quick action lengkap, smart scroll table",
  "2.3.76": "Tanggal libur interaktif, badge nasional, manajemen libur, smart scroll, tooltip tap-friendly",
  "2.3.75": "Kalender nasional Indonesia, konfigurasi Jumlah fleksibel, baris persentase dengan rumus",
  "2.3.74": "Rekap bulanan: urutan H/S/I/A/D, kolom Jumlah, baris Total, Hari Efektif sync, ekspor konsisten",
  "2.3.73": "Perbaikan presensi bulan lalu pada tab Harian, sinkronisasi data historis Supabase",
  "2.3.72": "Perbaikan tampilan ekspor tanda tangan, data siswa lengkap di preview, konsistensi format",
  "2.3.71": "Perbaikan minor UI presensi dan sinkronisasi data harian dengan rekap bulanan",
  "2.3.70": "Signature pada Ranking Siswa, Morphe Auto model badge, pagination 'Semua', changelog sync",
  "2.3.69": "Signature multi-signer, live preview, pagination semua, klarifikasi System Prompt vs Knowledge",
  "2.3.68": "Fix syntax error Attendance, fondasi integrasi tanda tangan ke ekspor",
  "2.3.67": "Signature Settings V2 schema, export signature utility untuk PDF/Excel/CSV",
  "2.3.66": "Rencana tanda tangan ekspor, Morphe sidebar truncation fix",
  "2.3.65": "Morphe Settings klarifikasi System Prompt vs Knowledge, minor UI improvements",
  "2.3.64": "Tim Pengembang persistence + social links, Morphe sidebar fix, kosongkan presensi massal",
  "2.3.63": "PageHeader breadcrumb, Morphe AI Settings, file preview dialog, Admin team management",
  "2.3.62": "Touch target 44px audit, mobile toolbar layout, Rapor Online plan, dark mode audit",
  "2.3.61": "Batch Import multi-sheet Excel, Portal Orang Tua detail nilai, Morphe SIPENA deep data consent",
  "2.3.60": "Sistem semester komprehensif dengan filtering year+semester, aggregation laporan",
  "2.3.59": "Fix ranking calculation weighted average, semester filter independent di Reports",
  "2.3.58": "Fix Morphe AI, Import Excel Siswa & Presensi, Export Loader Fix",
  "2.3.57": "Fix export loader repeated blank, Morphe chat fix, Portal data fix, Excel grade import",
  "2.3.56": "Fix export loader blank screen, Morphe sidebar truncation, camera capture, brand gradient",
  "2.3.55": "Morphe AI iterasi 3: file attachment, vision auto-switch, auto-summarize, GSAP glow",
  "2.3.54": "Morphe AI iterasi 2.5: session pinning, rename dialog, improved code blocks",
  "2.3.53": "Morphe AI iterasi 2: fullscreen, session management, code highlighting, SIPENA data analysis",
  "2.3.52": "Morphe AI Chat iterasi 1, ExportLoaderOverlay, Terms & Conditions page",
  "2.3.51": "Portal View real data, Reports portal card, GSAP export loader, Sidebar arrow fix",
  "2.3.50": "Calendar legend, Portal QR code & granular controls, Maintenance flyout, Database detail modal",
  "2.3.49": "Attendance monthly recap percentage formula, effective days badge, tooltip kelengkapan data",
  "2.3.48": "Persistent sidebar layout, Database Overview accurate counts with parallel fetching",
  "2.3.47": "Attendance preferences SQL, national holiday API sync, flexible Jumlah column config",
  "2.3.46": "Smart horizontal scroll table, popover tooltip tanggal rekap, ikon % dan i terpisah",
  "2.3.45": "Interactive holiday badge, holiday management override, drag-drop signature fix",
  "2.3.44": "Google OAuth Sign-In, reCAPTCHA v3 server-side verification via Edge Function",
  "2.3.43": "Export wrapping nama panjang, rekap bulanan fix, docs cleanup & README hierarki lengkap",
  "2.3.42": "Attendance note button always visible on mobile, Auth forgot password, PWA push notification",
  "2.3.41": "Ranking per mapel filter semester fix, null handling siswa tanpa data, formula konsisten",
  "2.3.40": "Toast deduplication, Activity logging CRUD hooks, Attendance mobile responsive fix",
  "2.3.39": "Daily attendance responsive fix, Calendar Indonesian, Mobile header, PNG 4K/HD export",
  "2.3.38": "Error Boundary, Skeleton Loading, Throttle Utility, XSS Fix, Calendar Consistent Styling",
  "2.3.37": "Pengaturan Presensi responsive fix, monthly recap left-align, auth error messages",
  "2.3.36": "UI overhaul menyeluruh, Calendar responsive fix, ScrollArea holidays/events",
  "2.3.35": "PNG export HD, batch day events, conflict handling, Global Search deep search",
  "2.3.34": "Readability fix, batch holiday, export overhaul & mobile precision",
  "2.3.33": "Perbaikan Presensi, ekspor full-width, header search & AI search",
  "2.3.32": "Presensi V2, Global Search, Auth Validation & AI Search Fix",
  "2.3.31": "Fix export PNG orientation, signature position persistence, student data complete preview",
  "2.3.30": "Signature export panel integrated, custom date field, font size options, line toggle",
  "2.3.29": "Multi-signer support up to 4 signers, hybrid storage DB + localStorage",
  "2.3.28": "Signature settings V2 JSONB schema, extended configuration fields",
  "2.3.27": "Export signature utility functions for PDF, Excel, CSV formats",
  "2.3.26": "Signature foundation integration into export dialogs",
  "2.3.25": "Export signature plan documentation, Morphe sidebar title truncation",
  "2.3.24": "Team developer management in Admin, reorder, toggle active/inactive",
  "2.3.23": "GSAP gradient animation on Morphe text, context menu sidebar fix",
  "2.3.22": "Refactor changelog data ke file terpisah",
  "2.3.21": "File preview dialog zoom rotate, PDF viewer, Office Online viewer",
  "2.3.20": "Morphe AI Settings panel system prompt, knowledge, history, SIPENA access",
  "2.3.19": "PageHeader reusable component with breadcrumb navigation",
  "2.3.18": "Touch target min 44px, mobile toolbar cleanup, dropdown grouped actions",
  "2.3.17": "Dark mode semantic token consistency, button sizing spacing Grades Attendance Classes",
  "2.3.16": "Batch import multi-sheet Excel ecosystem academic",
  "2.3.15": "Parent Portal detailed grades per subject assignment, status KKM",
  "2.3.14": "Morphe SIPENA deep data consent modal before accessing student details",
  "2.3.13": "Right-click context menu sidebar Morphe AI desktop Pin Rename Delete",
  "2.3.12": "Session sidebar Morphe title truncation ellipsis space for action buttons",
  "2.3.11": "Rapor Online Kurikulum Merdeka plan AI description OCR import merge fields",
  "2.3.10": "Performance database query indexing large reports, lazy loading heavy components",
  "2.3.9": "Filter semester independen Reports, smart year suggestions, reload switch periode",
  "2.3.8": "Perbaikan Ekspor Tanda Tangan & Preview Data - drag bebas, data lengkap, format konsisten",
  "2.3.7": "Sistem semester komprehensif v2 - hirarki Year→Semester, filtering komposit, SQL migration",
};
