-- Dynamic production monitoring configuration.
-- Secrets are stored in Supabase Vault and are only exposed through
-- service-role-only SECURITY DEFINER functions used by Edge Functions.

CREATE TABLE IF NOT EXISTS public.monitoring_settings (
  environment text PRIMARY KEY DEFAULT 'production'
    CHECK (environment = 'production'),
  enabled boolean NOT NULL DEFAULT false,
  minimum_severity text NOT NULL DEFAULT 'p1'
    CHECK (minimum_severity IN ('p1', 'p2', 'p3')),
  send_recovery boolean NOT NULL DEFAULT true,
  telegram_bot_secret_id uuid,
  telegram_chat_secret_id uuid,
  webhook_secret_id uuid,
  bot_username text,
  last_test_at timestamptz,
  last_test_success boolean,
  last_test_message text,
  updated_by text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.monitoring_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor text NOT NULL,
  action text NOT NULL,
  success boolean NOT NULL DEFAULT true,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.monitoring_incidents (
  fingerprint text PRIMARY KEY,
  monitor_name text NOT NULL,
  severity text NOT NULL CHECK (severity IN ('p1', 'p2', 'p3')),
  status text NOT NULL CHECK (status IN ('open', 'recovered')),
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  recovered_at timestamptz,
  occurrence_count integer NOT NULL DEFAULT 1 CHECK (occurrence_count > 0),
  last_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  telegram_open_sent boolean NOT NULL DEFAULT false,
  telegram_recovery_sent boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.monitoring_alert_nonces (
  nonce text PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS monitoring_audit_logs_created_at_idx
  ON public.monitoring_audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS monitoring_audit_logs_actor_action_idx
  ON public.monitoring_audit_logs (actor, action, created_at DESC);
CREATE INDEX IF NOT EXISTS monitoring_incidents_status_idx
  ON public.monitoring_incidents (status, last_seen_at DESC);
CREATE INDEX IF NOT EXISTS monitoring_alert_nonces_created_at_idx
  ON public.monitoring_alert_nonces (created_at);

INSERT INTO public.monitoring_settings (environment)
VALUES ('production')
ON CONFLICT (environment) DO NOTHING;

ALTER TABLE public.monitoring_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monitoring_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monitoring_incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monitoring_alert_nonces ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.monitoring_settings FORCE ROW LEVEL SECURITY;
ALTER TABLE public.monitoring_audit_logs FORCE ROW LEVEL SECURITY;
ALTER TABLE public.monitoring_incidents FORCE ROW LEVEL SECURITY;
ALTER TABLE public.monitoring_alert_nonces FORCE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.monitoring_settings FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.monitoring_audit_logs FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.monitoring_incidents FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.monitoring_alert_nonces FROM PUBLIC, anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.monitoring_settings TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.monitoring_audit_logs TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.monitoring_incidents TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.monitoring_alert_nonces TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.monitoring_audit_logs_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.monitoring_upsert_vault_secret(
  p_existing_id uuid,
  p_name text,
  p_value text,
  p_description text
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_id uuid := p_existing_id;
BEGIN
  IF p_value IS NULL OR btrim(p_value) = '' THEN
    RETURN v_id;
  END IF;

  IF v_id IS NULL THEN
    SELECT id INTO v_id
    FROM vault.secrets
    WHERE name = p_name
    ORDER BY created_at DESC
    LIMIT 1;
  END IF;

  IF v_id IS NOT NULL AND EXISTS (SELECT 1 FROM vault.secrets WHERE id = v_id) THEN
    PERFORM vault.update_secret(v_id, p_value, p_name, p_description);
    RETURN v_id;
  END IF;

  SELECT vault.create_secret(p_value, p_name, p_description) INTO v_id;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.monitoring_admin_get_config()
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT jsonb_build_object(
    'environment', s.environment,
    'enabled', s.enabled,
    'minimumSeverity', s.minimum_severity,
    'sendRecovery', s.send_recovery,
    'telegramBotConfigured', s.telegram_bot_secret_id IS NOT NULL
      AND EXISTS (SELECT 1 FROM vault.secrets v WHERE v.id = s.telegram_bot_secret_id),
    'telegramChatConfigured', s.telegram_chat_secret_id IS NOT NULL
      AND EXISTS (SELECT 1 FROM vault.secrets v WHERE v.id = s.telegram_chat_secret_id),
    'webhookConfigured', s.webhook_secret_id IS NOT NULL
      AND EXISTS (SELECT 1 FROM vault.secrets v WHERE v.id = s.webhook_secret_id),
    'telegramChatMasked', CASE
      WHEN chat.decrypted_secret IS NULL THEN NULL
      ELSE repeat('*', greatest(length(chat.decrypted_secret) - 4, 4)) || right(chat.decrypted_secret, 4)
    END,
    'botUsername', s.bot_username,
    'lastTestAt', s.last_test_at,
    'lastTestSuccess', s.last_test_success,
    'lastTestMessage', s.last_test_message,
    'updatedBy', s.updated_by,
    'updatedAt', s.updated_at
  )
  FROM public.monitoring_settings s
  LEFT JOIN vault.decrypted_secrets chat ON chat.id = s.telegram_chat_secret_id
  WHERE s.environment = 'production';
$$;

CREATE OR REPLACE FUNCTION public.monitoring_get_runtime_config()
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT jsonb_build_object(
    'enabled', s.enabled,
    'minimumSeverity', s.minimum_severity,
    'sendRecovery', s.send_recovery,
    'telegramBotToken', bot.decrypted_secret,
    'telegramChatId', chat.decrypted_secret,
    'webhookKey', webhook.decrypted_secret,
    'botUsername', s.bot_username,
    'updatedAt', s.updated_at
  )
  FROM public.monitoring_settings s
  LEFT JOIN vault.decrypted_secrets bot ON bot.id = s.telegram_bot_secret_id
  LEFT JOIN vault.decrypted_secrets chat ON chat.id = s.telegram_chat_secret_id
  LEFT JOIN vault.decrypted_secrets webhook ON webhook.id = s.webhook_secret_id
  WHERE s.environment = 'production';
$$;

CREATE OR REPLACE FUNCTION public.monitoring_admin_save_config(
  p_enabled boolean,
  p_minimum_severity text,
  p_send_recovery boolean,
  p_bot_token text DEFAULT NULL,
  p_chat_id text DEFAULT NULL,
  p_webhook_key text DEFAULT NULL,
  p_bot_username text DEFAULT NULL,
  p_actor text DEFAULT 'admin'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_settings public.monitoring_settings%ROWTYPE;
  v_bot_id uuid;
  v_chat_id uuid;
  v_webhook_id uuid;
BEGIN
  IF p_minimum_severity NOT IN ('p1', 'p2', 'p3') THEN
    RAISE EXCEPTION 'Tingkat severity tidak valid';
  END IF;

  INSERT INTO public.monitoring_settings (environment)
  VALUES ('production')
  ON CONFLICT (environment) DO NOTHING;

  SELECT * INTO v_settings
  FROM public.monitoring_settings
  WHERE environment = 'production'
  FOR UPDATE;

  v_bot_id := public.monitoring_upsert_vault_secret(
    v_settings.telegram_bot_secret_id,
    'sipena_monitor_telegram_bot_token',
    p_bot_token,
    'Telegram bot token for SIPENA production monitoring'
  );
  v_chat_id := public.monitoring_upsert_vault_secret(
    v_settings.telegram_chat_secret_id,
    'sipena_monitor_telegram_chat_id',
    p_chat_id,
    'Telegram chat id for SIPENA production monitoring'
  );
  v_webhook_id := public.monitoring_upsert_vault_secret(
    v_settings.webhook_secret_id,
    'sipena_monitor_webhook_key',
    p_webhook_key,
    'HMAC webhook key for SIPENA production monitoring'
  );

  UPDATE public.monitoring_settings
  SET enabled = p_enabled,
      minimum_severity = p_minimum_severity,
      send_recovery = p_send_recovery,
      telegram_bot_secret_id = v_bot_id,
      telegram_chat_secret_id = v_chat_id,
      webhook_secret_id = v_webhook_id,
      bot_username = COALESCE(NULLIF(p_bot_username, ''), bot_username),
      updated_by = p_actor,
      updated_at = now()
  WHERE environment = 'production';

  INSERT INTO public.monitoring_audit_logs (actor, action, success, details)
  VALUES (
    p_actor,
    'save_config',
    true,
    jsonb_build_object(
      'enabled', p_enabled,
      'minimumSeverity', p_minimum_severity,
      'sendRecovery', p_send_recovery,
      'botTokenRotated', p_bot_token IS NOT NULL AND btrim(p_bot_token) <> '',
      'chatIdChanged', p_chat_id IS NOT NULL AND btrim(p_chat_id) <> '',
      'webhookKeyRotated', p_webhook_key IS NOT NULL AND btrim(p_webhook_key) <> ''
    )
  );

  RETURN public.monitoring_admin_get_config();
END;
$$;

CREATE OR REPLACE FUNCTION public.monitoring_admin_record_test(
  p_success boolean,
  p_message text,
  p_bot_username text,
  p_actor text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.monitoring_settings
  SET last_test_at = now(),
      last_test_success = p_success,
      last_test_message = left(COALESCE(p_message, ''), 500),
      bot_username = COALESCE(NULLIF(p_bot_username, ''), bot_username),
      updated_by = p_actor,
      updated_at = now()
  WHERE environment = 'production';

  INSERT INTO public.monitoring_audit_logs (actor, action, success, details)
  VALUES (
    p_actor,
    'telegram_test',
    p_success,
    jsonb_build_object('message', left(COALESCE(p_message, ''), 200))
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.monitoring_admin_disconnect_telegram(p_actor text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_bot_id uuid;
  v_chat_id uuid;
BEGIN
  SELECT telegram_bot_secret_id, telegram_chat_secret_id
  INTO v_bot_id, v_chat_id
  FROM public.monitoring_settings
  WHERE environment = 'production'
  FOR UPDATE;

  UPDATE public.monitoring_settings
  SET enabled = false,
      telegram_bot_secret_id = NULL,
      telegram_chat_secret_id = NULL,
      bot_username = NULL,
      last_test_at = NULL,
      last_test_success = NULL,
      last_test_message = NULL,
      updated_by = p_actor,
      updated_at = now()
  WHERE environment = 'production';

  DELETE FROM vault.secrets WHERE id IN (v_bot_id, v_chat_id);

  INSERT INTO public.monitoring_audit_logs (actor, action, success, details)
  VALUES (p_actor, 'disconnect_telegram', true, '{}'::jsonb);

  RETURN public.monitoring_admin_get_config();
END;
$$;

REVOKE ALL ON FUNCTION public.monitoring_upsert_vault_secret(uuid, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.monitoring_admin_get_config() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.monitoring_get_runtime_config() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.monitoring_admin_save_config(boolean, text, boolean, text, text, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.monitoring_admin_record_test(boolean, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.monitoring_admin_disconnect_telegram(text) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.monitoring_admin_get_config() TO service_role;
GRANT EXECUTE ON FUNCTION public.monitoring_get_runtime_config() TO service_role;
GRANT EXECUTE ON FUNCTION public.monitoring_admin_save_config(boolean, text, boolean, text, text, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.monitoring_admin_record_test(boolean, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.monitoring_admin_disconnect_telegram(text) TO service_role;

NOTIFY pgrst, 'reload schema';
